variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  SG_JAVA_BUILD_VERSION: "11"

image: maven:3.6-jdk-${SG_JAVA_BUILD_VERSION}

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
  - .m2/repository

before_script:
- rm -rf /var/lib/apt/lists/* && apt-get update -yqq && apt-get install -yqq apt-utils jq perl libapr1 openssl libxml2-utils curl uuid-runtime ftp gnupg2 pinentry-tty expect psmisc xmlstarlet
- echo "VERSIONS:"
- uname -a;java -version;openssl version

stages:
- test
- deploy

verify:
  stage: test
  script:
  - sudo ./smoketest.sh
  - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then mvn -U -Pcoverage verify; else mvn -U verify; fi
  artifacts:
    reports:
      junit:
      - target/surefire-reports/TEST-*.xml
deploy:
  stage: deploy
  only:
    variables:
    - $CI_COMMIT_REF_NAME == "master"
  script:
  - mvn deploy -U -Penterprise -DskipTests -s settings.xml
  #    - mvn -U -Pcoverage sonar:sonar -Dsonar.organization=floragunncom-github -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=https://sonarcloud.io || true
  - mvn clean verify com.srcclr:srcclr-maven-plugin:scan -Penterprise -DskipTests -U
#    -./dev/scan_veracode.sh
